### ISSUE TITLE
Bot Crashing!

### ISSUE THREAD

**Issue by seanpool3** [dtcarls/ff_bot#26]
The bot keeps crashing for me... here is the traceback of the error.

2018-09-12T03:32:33.220122+00:00 app[worker.1]: Traceback (most recent call last):
2018-09-12T03:32:33.220141+00:00 app[worker.1]:   File "ff_bot/ff_bot.py", line 245, in <module>
2018-09-12T03:32:33.220818+00:00 app[worker.1]:     bot_main("init")
2018-09-12T03:32:33.220820+00:00 app[worker.1]:   File "ff_bot/ff_bot.py", line 220, in bot_main
2018-09-12T03:32:33.221093+00:00 app[worker.1]:     bot.send_message(text)
2018-09-12T03:32:33.221096+00:00 app[worker.1]:   File "ff_bot/ff_bot.py", line 32, in send_message
2018-09-12T03:32:33.221267+00:00 app[worker.1]:     raise GroupMeException('Invalid BOT_ID')
2018-09-12T03:32:33.221300+00:00 app[worker.1]: __main__.GroupMeException: Invalid BOT_ID

I have tried to re enter and change the groupme bot id, but it isnt working.  Help please!

**Comment by dtcarls** [comment]
Have you deployed the latest version and/or removed (not made blank) your init_msg environment variable?

**Comment by seanpool3** [comment]
Thanks so much for the help!

I re-deployed the latest version and removed the init_msg variable on heroku...

trying to view the app I got another error...

Here is the log

2018-09-12T14:39:25.066836+00:00 heroku[router]: at=error code=H14 desc="No web processes running" method=GET path="/" host=shivabot12.herokuapp.com request_id=77a136c8-472c-4ee2-bf23-5474335ce1fd fwd="75.82.187.147" dyno= connect= service= status=503 bytes= protocol=https
2018-09-12T14:39:25.483655+00:00 heroku[router]: at=error code=H14 desc="No web processes running" method=GET path="/favicon.ico" host=shivabot12.herokuapp.com request_id=56ccaade-1f94-4c47-9f45-da682aaaa4ad fwd="75.82.187.147" dyno= connect= service= status=503 bytes= protocol=https

Not sure what is going wrong!

**Comment by dtcarls** [comment]
Which chat program are you attempting to use the bot with?

**Comment by seanpool3** [comment]
Groupme! Hopefully it will work now. Thanks so much!
